title: Iranhoe
description: Página de tecnología y blog
url: "https://blog.homeserver.com"
author: iranhoe

timezone: UTC
lang: es

# Chirpy Theme
theme: jekyll-theme-chirpy

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-polyglot
  - jekyll-include-cache

# Polyglot
languages: [es, en]
default_lang: es
exclude_from_localizations: [assets, redirect_from]

# Pagination
paginate: 10
paginate_path: '/page:num'

# Archives
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Social
social:
  name: Iran Corrales Becerra
  email: iran@example.com
  links:
    - https://github.com/iranhoe
    - https://twitter.com/iranhoe

# Chirpy specific settings
github:
  username: iranhoe
twitter:
  username: iranhoe

img_path: /assets/img
avatar: /assets/img/avatar.png

tabs:
  - title: ARCHIVES
    url: /archives/
    icon: fas fa-archive
    order: 1
  - title: CATEGORIES
    url: /categories/
    icon: fas fa-folder-open
    order: 2
  - title: TAGS
    url: /tags/
    icon: fas fa-tags
    order: 3
  - title: ABOUT
    url: /about/
    icon: fas fa-info-circle
    order: 4

