title: Iranhoe
description: Página de tecnología y blog

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "www.iranhoe.com" # change this to the base hostname & protocol for your site

google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%-d %b %Y"

theme: # leave it empty

# social
author: iranhoe
image: /thumbnail-jumbo.png
github:
  owner_name: iran corrales becerra
twitter:
  username: iranhoe

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['blog', 'about']

disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: iranhoe-github-io
